"""add assigned_day column to day

Revision ID: 8ec0dbf08218
Revises: a98b3e78bdb2
Create Date: 2022-02-22 08:59:52.103767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ec0dbf08218'
down_revision = 'a98b3e78bdb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('days', sa.Column('assigned_day', sa.String(50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('days', 'assigned_day')
    # ### end Alembic commands ###
