"""add assigned boolean to day table

Revision ID: a98b3e78bdb2
Revises: 0e6df04b9dc1
Create Date: 2022-02-21 14:06:43.677498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a98b3e78bdb2'
down_revision = '0e6df04b9dc1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('days', sa.Column('assigned', sa.Boolean(), nullable=True, default=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('days', 'assigned')
    # ### end Alembic commands ###
