"""add boolean template column to day table

Revision ID: 4592ca0b9428
Revises: 83eefdd74711
Create Date: 2022-04-14 10:06:44.065474

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4592ca0b9428'
down_revision = '83eefdd74711'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('days', sa.Column('template', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('days', 'template')
    # ### end Alembic commands ###
