"""add user_id column to exercises table

Revision ID: 83eefdd74711
Revises: 52781a3ff719
Create Date: 2022-04-06 15:22:34.384707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83eefdd74711'
down_revision = '52781a3ff719'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercises', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'exercises', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint(None, 'exercises', type_='foreignkey')
    op.drop_column('exercises', 'user_id')
    # ### end Alembic commands ###
