"""new assoc table

Revision ID: 0e6df04b9dc1
Revises: 37142da9b9a3
Create Date: 2022-02-17 15:43:23.820599

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0e6df04b9dc1'
down_revision = '37142da9b9a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('DaysExercises',
    sa.Column('day_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('goal', sa.String(length=30), nullable=True),
    sa.Column('actual', sa.String(length=30), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['day_id'], ['days.id'], ),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.PrimaryKeyConstraint('day_id', 'exercise_id')
    )
    op.alter_column('splits', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('splits', 'start_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('splits', 'start_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('splits', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_table('DaysExercises')
    # ### end Alembic commands ###
