"""created_at columns

Revision ID: 8ce42f1ca951
Revises: 8ec0dbf08218
Create Date: 2022-02-25 07:09:53.709945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ce42f1ca951'
down_revision = '8ec0dbf08218'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('DaysExercises', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('days', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('exercises', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('splits', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('splits', 'created_at')
    op.drop_column('exercises', 'created_at')
    op.drop_column('days', 'created_at')
    op.drop_column('DaysExercises', 'created_at')
    # ### end Alembic commands ###
