"""add end_date to split table

Revision ID: 52781a3ff719
Revises: 8ce42f1ca951
Create Date: 2022-04-05 11:22:04.269325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52781a3ff719'
down_revision = '8ce42f1ca951'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('splits', sa.Column('end_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('splits', 'end_date')
    # ### end Alembic commands ###
